### ISSUE TITLE
Formatting is not working

### ISSUE THREAD

**Issue by aridgupta** [jose-elias-alvarez/nvim-lsp-ts-utils#30] opened 2021-06-03 07:27 UTC
I am on the `develop` branch and formatting isn't working. Here is my `ts_utils` and `null_ls` config.

`require("null-ls").setup {}`

```
        local ts_utils = require("nvim-lsp-ts-utils")

        -- defaults
        ts_utils.setup {
            debug = false,
            disable_commands = false,
            enable_import_on_completion = true,
            import_on_completion_timeout = 500,

            -- eslint
            eslint_enable_code_actions = true,
            eslint_bin = "eslint_d",
            eslint_args = {"-f", "json", "--stdin", "--stdin-filename", "$FILENAME"},
            eslint_enable_disable_comments = true,

	    -- experimental settings!
            -- eslint diagnostics
            eslint_enable_diagnostics = false,
            eslint_diagnostics_debounce = 250,

            -- formatting
            enable_formatting = true,
            formatter = "prettier",
            format_on_save = true,
            no_save_after_format = false,

            -- parentheses completion
            complete_parens = true,
            signature_help_in_parens = false,

	    -- update imports on file move
	          update_imports_on_move = true,
	          require_confirmation_on_move = true,
            debug = true
        }

        -- required to enable ESLint code actions and formatting
        ts_utils.setup_client(client)

```

**Comment by jose-elias-alvarez** [comment] 2021-06-03 08:21
Thanks for posting this! I've verified a (well-intentioned, but misleading) bit of behavior in null-ls that might have led users to believe that formatting wasn't working, and I've verified that formatting works with your config on the latest version of null-ls. 

First of all, could you please try updating both plugins, then running `vim.lsp.buf.formatting()` and see if it formats the buffer as expected?

If that doesn't work, could you please verify the following?

1. I've added debug logs to this plugin's null-ls integration setup. Could you check whether the plugin is correctly enabling and registering the integrations you've enabled?

2. Have you set `client.resolved_capabilities.document_formatting = false` in your `tsserver` `on_attach` function?

3. Is `prettier` available on your `$PATH`, or is it a local dependency? In either case, does the `debug` output show that the executable was resolved correctly?

4. How are you attempting to format the document? Are you using any autocommands or other plugins that could conflict with formatting?

**Comment by aridgupta** [comment] 2021-06-03 12:48
> First of all, could you please try updating both plugins, then running vim.lsp.buf.formatting() and see if it formats the buffer as expected?

It doesn't.

> I've added debug logs to this plugin's null-ls integration setup. Could you check whether the plugin is correctly enabling and registering the integrations you've enabled?

Yes, it is correctly registering all the integrations.

> Have you set client.resolved_capabilities.document_formatting = false in your tsserver on_attach function?

Yes

> Is prettier available on your $PATH, or is it a local dependency? In either case, does the debug output show that the executable was resolved correctly?

It is installed globally and the debug output shows that the executable was resolved correctly.

> How are you attempting to format the document? Are you using any autocommands or other plugins that could conflict with formatting?

I am just setting the option of `format_on_save` to `true`.

I can see that the buffer is modified but the buffer doesn't reflect the changes. For example, if I have unnecessary empty lines, I can see that the buffer is modified on save but those lines are not geting deleted.

**Comment by jose-elias-alvarez** [comment] 2021-06-03 13:39
The `format_on_save` option on this plugin actually doesn't have any effect on the `develop` branch. A few of the options in your config have been removed, but I don't think they should have a negative effect – the plugin will just ignore them, and either way, formatting should work when you run `vim.lsp.buf.formatting()`. 

A few more questions to help figure this out:

1. When you run `:LspInfo` after opening a TypeScript file, do you see both `tsserver` and `null-ls` listed under `Clients attached to this buffer`?

2. I assume you've already tested this, but just to verify, does Prettier run without any issues on the same file from the command line? Also, does the same issue occur across multiple files / projects?

3. Where are you calling `require("null-ls").setup {}`? To make sure this isn't the issue, could you try moving it inside your `tsserver` `on_attach` callback (if it's not already there)?

4. I added a quick `debug` option to null-ls, since I suspect the issue is that Prettier is outputting something to `stderr`, which causes formatting to fail. Could you please update it and try changing your null-ls config to `require("null-ls").setup {debug = true}`, then look at the output in `:messages`?

**Comment by aridgupta** [comment] 2021-06-03 14:11
> When you run :LspInfo after opening a TypeScript file, do you see both tsserver and null-ls listed under Clients attached to this buffer?

It doesn't show null-ls

> 

I assume you've already tested this, but just to verify, does Prettier run without any issues on the same file from the command line? Also, does the same issue occur across multiple files / projects?

It works from the command line.

> Where are you calling require("null-ls").setup {}? To make sure this isn't the issue, could you try moving it inside your tsserver on_attach callback (if it's not already there)?

Made this change but still no luck :(

> I added a quick debug option to null-ls, since I suspect the issue is that Prettier is outputting something to stderr, which causes formatting to fail. Could you please update it and try changing your null-ls config to require("null-ls").setup {debug = true}, then look at the output in :messages after running the command :lua vim.lsp.buf.formatting()?

No error logs in `:messages`.

**Comment by jose-elias-alvarez** [comment] 2021-06-03 14:57
Alright, let's give this a try. I put together a repository containing a minimal `init.vim`, which will work if you're using packer.nvim (and should work with other plugin managers, though I'm far from an expert).

Could you please try cloning the repository, which is available [here](https://github.com/jose-elias-alvarez/ts-utils-formatting), and following these exact steps?

1. Run `npm install` to make sure we're using a local Prettier executable
2. Run `nvim --noplugin -u minimal.vim test.js` from the command line
3. In Neovim, run `:lua vim.lsp.buf.formatting()`
4. Verify if the buffer was formatted and if you see output in `:messages`

If that doesn't work, I'm afraid we might be stuck, since there's not much more I can do to debug if you're not getting any output from null-ls. The only thing I'd have left to look at is your full LSP config, to see if there's any potential conflicts there. Other than that, I'd recommend setting up another formatting solution.

**Comment by aridgupta** [comment] 2021-06-03 15:10
While running `nvim --noplugin -u minimal.vim test.js`, it says `null-ls` not found. Although I can see that it is installed and can be found inside the `plugins` folder.

I am using vim-plug to install plugins. And to install `null-ls` I am using this statement `Plug 'jose-elias-alvarez/null-ls.nvim', { 'branch': 'main' }`.

**Comment by jose-elias-alvarez** [comment] 2021-06-03 15:27
I tried modifying the `rtp` setting to work with vim-plug, assuming you're using the default directory (if not, it should be simple to modify it based on the example). Could you pull the changes and give it another try?

**Comment by jose-elias-alvarez** [comment] 2021-06-03 15:43
Okay, I think I might have figured it out! I think it comes down to the fact that packer.nvim and vim-plug use different mechanisms to set `rtp`. With packer.nvim, the null-ls server has access to Lua modules, but with vim-plug it does not. I was able to tweak the arguments used to start the null-ls server so that vim-plug should be okay, too. 

Could you please try uninstalling and reinstalling null-ls using `{ 'branch': 'fix-path' }` and see if that works?

**Comment by aridgupta** [comment] 2021-06-03 16:06
Okay, I tried reinstalling null-ls. Now, it is loading properly. However, formatting still doesn't work. This is odd because it was working previously before all the updates and switching to `develop` branch on the `ts-utils` plugin.

**Comment by jose-elias-alvarez** [comment] 2021-06-03 16:10
What does the null-ls debug output look like in `:messages` when you run `:lua vim.lsp.buf.formatting()`?

The previous formatting implementation was closer to something like [neoformat](https://github.com/sbdchd/neoformat), which is a good option if we can't figure this out.

**Comment by aridgupta** [comment] 2021-06-03 16:18
Okay, now `:lua vim.lsp.buf.formatting_sync()` formats the file and then saves it. But how do I make it work with the plugin? I have `enable_formatting` set to `true` inside the config.

**Comment by jose-elias-alvarez** [comment] 2021-06-03 16:27
Okay, we're almost there! `enable_formatting` sets up the null-ls integration, but the plugin doesn't do anything beyond that (though I can see that I might want to streamline the process). 

If you want to enable formatting on save, you can add this to your `tsserver` `on_attach` function:

```lua
vim.cmd("autocmd BufWritePost <buffer> lua vim.lsp.buf.formatting()")
```

You could also set up an alias for the formatting command in the same place, if that's easier:
```lua
vim.cmd("command -buffer Formatting lua vim.lsp.buf.formatting()")
```

**Comment by aridgupta** [comment] 2021-06-03 16:33
It's a thing of beauty now. Organize imports and format on save working flawlessly. Thank you so much for your hard work and patience. I would try to setup `prettier_d_slim` as it's much faster than `prettier`.

One more question, why isn't `prettierd` supported by the plugin? It works flawlessly and it's so fast.

This question is completely out of context. Could you please if possible point to me to some resources where I could learn vim plugin development in lua?

Thanks again :)

**Comment by jose-elias-alvarez** [comment] 2021-06-03 16:49
Fantastic! Thank you so much for your patience working through this. It was a pretty serious bug that I never would have caught without your help. 

I actually hadn't heard of `prettierd` but it should be simple to put in support, so I'll work on that next. 

For Lua plugins, I started with [this article](https://learnxinyminutes.com/docs/lua/), which gives an overview of the language if you're not already familiar, [this repo](https://github.com/nanotee/nvim-lua-guide), which describes how Neovim and Lua interact, and [this video](https://www.youtube.com/watch?v=6ch28A_YICQ), which does a pretty good job describing the basic plugin structure. After that, I think the best thing to do is to find a small project to work on (converting a Vimscript plugin to Lua is a good place to start) and learn as you go. Reddit and the Neovim Gitter are both helpful. 

Going to go ahead and close this for now, but let me know if you run into any issues or have any questions about Lua plugins.

**Closed by jose-elias-alvarez** 2021-06-03 16:49 UTC
