### ISSUE TITLE
Some problems with the new ESLint code actions functionality

### ISSUE THREAD

**Issue by VVKot** [jose-elias-alvarez/nvim-lsp-ts-utils#7] opened 2021-04-17 12:04 UTC
Just wanted to start off by saying thanks for implementing this, we're a step closer to feature parity with CoC!

I tried it out and found several problems:

1. Boolean parameter seems to be required here in the latest neovim:
https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils/blob/ef83962fe4f462753dede81f7505a6f9449cd512/lua/nvim-lsp-ts-utils/code-action-handler.lua#L183
2. Same here for the third parameter, I simply added `function() end`:
https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils/blob/ef83962fe4f462753dede81f7505a6f9449cd512/lua/nvim-lsp-ts-utils/code-action-handler.lua#L187-L190
3. After that `lua vim.lsp.buf.code_action()` successfully returns actions 🎉  - but Telescope's `lsp_code_actions` does not.

**Comment by jose-elias-alvarez** [comment] 2021-04-17 12:26
Thank you for looking into it! I've gone ahead and merged the changes. I wasn't having any issues with my Neovim version, but I don't update as often as I should. I also fixed a utility function that was failing to report potential errors with ESLint output, and I want to learn more about `libuv` error handling in general to catch issues like this earlier. 

Re: Telescope: the issue is that the plugin bypasses the defined code handler and fetches code actions directly from the language server, so it's not possible to inject the ESLint code actions in the same way. I'll open up another issue, since it would be a nice feature to have.

**Closed by jose-elias-alvarez** 2021-04-17 12:26 UTC
